FROM n8nio/n8n

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV NODE_ENV=production
ENV N8N_PUSH_BACKEND=polling

# timezone
ENV GENERIC_TIMEZONE=Europe/Amsterdam

# Optional extra packages
ENV N8N_ADDITIONAL_NPM_PACKAGES=xml2js

EXPOSE 5678